on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: eefefefregistry.azurecr.io
        username: ${{ secrets.acr_eefefefregistry_username }}
        password: ${{ secrets.acr_eefefefregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t eefefefregistry.azurecr.io/eefefef:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push eefefefregistry.azurecr.io/eefefef:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_eefefef_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep eefefefad6c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace eefefefad6c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: eefefefad6c
        container-registry-url: eefefefregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_eefefefregistry_username }}
        container-registry-password: ${{ secrets.acr_eefefefregistry_password }}
        secret-name: eefefefdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: eefefefad6c
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          eefefefregistry.azurecr.io/eefefef:${{ github.sha }}
        imagepullsecrets: |
          eefefefdockerauth
