name: Trigger auto deployment for xxxxccx

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/xxxxccx-AutoDeployTrigger-099166f3-6cc2-4d48-ac0a-7c6e63e347af.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: eefefefregistry.azurecr.io
          username: ${{ secrets.XXXXCCX_REGISTRY_USERNAME }}
          password: ${{ secrets.XXXXCCX_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eefefefregistry.azurecr.io/xxxxccx:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.XXXXCCX_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n xxxxccx -g DefaultResourceGroup-EUS --server eefefefregistry.azurecr.io --username  ${{ secrets.XXXXCCX_REGISTRY_USERNAME }} --password ${{ secrets.XXXXCCX_REGISTRY_PASSWORD }}
            az containerapp update -n xxxxccx -g DefaultResourceGroup-EUS --image eefefefregistry.azurecr.io/xxxxccx:${{ github.sha }}
